import Head from 'next/head'
import styles from './MainLayout.module.css'

interface IMainLayout {
  title: string;
  children: any;
}

const MainLayout = ({ title, children }: IMainLayout) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {
          children
        }

      </main>
    </div>
  )
}

export { MainLayout }