import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MainLayout } from '../components/mainLayout/MainLayout'
import { ButtonsLayout } from '../components/buttonsLayout/ButtonsLayout'
import { PageTitle } from '../components/pageTitle/PageTitle'
import { Notification } from '../components/notification/Notification'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aula POO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>

        <ButtonsLayout />

        <PageTitle title="Avisos da Aula de POO"/>

        <Notification />

      </MainLayout>
    </div>
  )
}
